import Head from 'next/head'
import MainLayout from '../components/MainLayout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Alex S.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        Content
      </MainLayout>
    </div>
  )
}
